version: "3.9"

services:
  app:
    build: ./docker/php
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin:5
    container_name: phpmyadmin_gpt_study
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
